name: Release Charts

on:
  push:
    branches:
      - main

jobs:
  release:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v5
        with:
          fetch-depth: 0

      - name: Configure Git
        run: |
          git config user.name "$GITHUB_ACTOR"
          git config user.email "$GITHUB_ACTOR@users.noreply.github.com"

      - name: Set up Helm
        uses: azure/setup-helm@v4

      - name: Add Helm repos
        run: helm repo add bitnami https://charts.bitnami.com/bitnami

      - name: Import GPG key
        id: import_gpg
        uses: crazy-max/ghaction-import-gpg@v6
        with:
          gpg_private_key: ${{ secrets.HELM_GPG_PRIVATE_KEY }}
          passphrase: ${{ secrets.HELM_GPG_PASSPHRASE }}

      - name: Create legacy GnuPG rings for Helm
        run: |
          mkdir -p /home/runner/.gnupg
          gpg --batch --yes --export > /home/runner/.gnupg/pubring.gpg
          gpg --batch --yes --export-secret-keys > /home/runner/.gnupg/secring.gpg

      - name: Run chart-releaser
        uses: helm/chart-releaser-action@v1.7.0
        env:
          CR_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
          CR_SIGN: "true"
          CR_KEY: "${{ steps.import_gpg.outputs.keyid }}"
          CR_PASSPHRASE: "${{ secrets.HELM_GPG_PASSPHRASE }}"
          CR_KEYRING: "/home/runner/.gnupg/pubring.gpg"

      - name: Backup README.md
        run: |
          cp README.md ..

      - name: Checkout gh-pages branch
        uses: actions/checkout@v5
        with:
          ref: gh-pages

      - name: Copy README.md to gh-pages
        run: |
          cp ../README.md .

      - name: Commit and push changes to gh-pages
        run: |
          git config user.name "$GITHUB_ACTOR"
          git config user.email "$GITHUB_ACTOR@users.noreply.github.com"
          git add README.md
          git commit -m "Update README.md"
          git push origin gh-pages
